Repository kakao-tech-campus-2nd-step3/Team26_BE, pull requests merged in 2024-11, with the labels that each got.

#139 [Weekly/11/Refactor/TokenResponse] token response에 사용자 아이디, 타입 반환하도록 반영
  src/main/java/org/ktc2/cokaen/wouldyouin/_develop/api/TempCreateController.java
  src/main/java/org/ktc2/cokaen/wouldyouin/auth/api/dto/SocialTokenResponse.java
  src/main/java/org/ktc2/cokaen/wouldyouin/auth/api/dto/TokenResponse.java
  src/main/java/org/ktc2/cokaen/wouldyouin/auth/application/AuthService.java
Labels: ♻️Refactor

#144 [Weekly/11/Hotfix/brokenBuild] 빌드 실패 오류 수정
  src/main/java/org/ktc2/cokaen/wouldyouin/like/application/dto/LikeResponse.java
  src/main/java/org/ktc2/cokaen/wouldyouin/like/application/dto/LikeToggleResponse.java
Labels: 🐛Fix

#146 [Weekly/11/Test/Event] EventServiceUnitTest 작성
  src/main/java/org/ktc2/cokaen/wouldyouin/event/application/EventService.java
  src/test/java/org/ktc2/cokaen/wouldyouin/_global/testdata/CommonData.java
  src/test/java/org/ktc2/cokaen/wouldyouin/_global/testdata/EventData.java
  src/test/java/org/ktc2/cokaen/wouldyouin/event/EventServiceUnitTest.java
Labels: ✨Feature
